name: delta
description:  "delta"

environment:
   sdk: '>=2.0.0'

dependencies:
  sprintf: any
  chronosgl:
    path: ../ChronosGL
  vector_math: ">=2.0.5 <3.0.0"

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any

